{"name": "人脸信息管理--访客修改功能", "status": "skipped", "statusDetails": {"message": "Skipped: 普利人脸服务连接目前不可用", "trace": "('TestCases\\\\Test3_FaceRecognition\\\\test_1_face_info_manage.py', 37, 'Skipped: 普利人脸服务连接目前不可用')"}, "parameters": [{"name": "data", "value": "{'case_id': 2, 'sheet_name': 'face_info_modify', 'title': '正常添加', 'modify_face_info': '系统管理员', 'name': None, 'employee': '系统管理员', 'gender': '男', 'telephone_number': None, 'id_card_number': '421023199902012102', 'company': None, 'dirpath': 'C:\\\\Users\\\\yyzz\\\\Desktop\\\\图片\\\\face\\\\customer_modify', 'smartwatch': '新增-智能手表001'}"}], "start": 1607074566252, "stop": 1607074566252, "uuid": "2b395352-6cd5-4790-aa64-c7bee80ecd0c", "historyId": "f242d689a0e11533d282b79575a4cd56", "testCaseId": "b22f77b3208e9efb6fd503cc1211b711", "fullName": "TestCases.Test3_FaceRecognition.test_1_face_info_manage.TestFaceRecognition#test_modify_face_info", "labels": [{"name": "feature", "value": "人脸识别"}, {"name": "epic", "value": "项目名称：中控平台V2.1"}, {"name": "story", "value": "人脸信息管理"}, {"name": "tag", "value": "@pytest.mark.skip(reason='普利人脸服务连接目前不可用')"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh')"}, {"name": "parentSuite", "value": "TestCases.Test3_FaceRecognition"}, {"name": "suite", "value": "test_1_face_info_manage"}, {"name": "subSuite", "value": "TestFaceRecognition"}, {"name": "host", "value": "DESKTOP-901EL0R"}, {"name": "thread", "value": "9616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.Test3_FaceRecognition.test_1_face_info_manage"}]}